version: "3.7"

services:
  api-service:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - api-network
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
    volumes:
      - ./database/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    ports:
      - 3306
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
